#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
K8S_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
# shellcheck disable=SC1091
. "$K8S_DIR/config.env"

mkdir -p "$K8S_DIR/manifests"

fetch() {
  name=$1
  url=$2
  out=$3
  if [ -z "$url" ]; then
    echo "skip $name: URL not configured" >&2
    return 0
  fi
  echo "fetch $name: $url" >&2
  curl -fsSL "$url" -o "$out"
}

fetch calico "$CALICO_MANIFEST_URL" "$K8S_DIR/manifests/calico.yaml"
fetch metrics-server "$METRICS_SERVER_MANIFEST_URL" "$K8S_DIR/manifests/metrics-server.yaml"

cat > "$K8S_DIR/manifests/README.md" <<EOF
# Manifests

Generated by k8s/tools/sync-manifests.sh.

Run this before publishing CN packages:

  IMAGE_MIRROR_PREFIX=$IMAGE_MIRROR_PREFIX ./tools/rewrite-images.sh manifests/
EOF

echo "sync completed"
